# Generated by Django 5.2.12 on 2026-07-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "Cash on Delivery"),
                    ("esewa", "eSewa"),
                    ("khalti", "Khalti"),
                ],
                default="cod",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(default="pending", max_length=10),
        ),
        migrations.AddField(
            model_name="order",
            name="transaction_uuid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
