# Generated by Django 5.2.12 on 2026-08-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_productimage_options_plantdetails_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
