# Generated by Django 5.2.12 on 2026-08-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_remove_product_image_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="product",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
