# Generated by Django 5.2.12 on 2026-08-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_order_order_status_order_updated_at_order_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cod", "Cash on Delivery"), ("esewa", "eSewa")],
                default="cod",
                max_length=10,
            ),
        ),
    ]
