# Generated by Django 5.2.12 on 2026-08-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="product",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="user",
        ),
        migrations.RemoveField(
            model_name="product",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="product",
            name="review_count",
        ),
        migrations.RemoveField(
            model_name="product",
            name="views",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="rating",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
