# Generated by Django 5.2.12 on 2026-03-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flowers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flower",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="flowers/"),
        ),
    ]
