# Generated by Django 5.2.12 on 2026-03-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flowers", "0002_flower_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bouquet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="bouquets/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("flowers", models.ManyToManyField(to="flowers.flower")),
            ],
        ),
    ]
