# Generated by Django 5.2.12 on 2026-07-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flowers", "0004_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquet",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="flower",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
